/**
 * @fileoverview gRPC-Web generated client stub for transcription
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: transcription.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.transcription = require('./transcription_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.transcription.TranscriptionServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.transcription.TranscriptionServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.transcription.AudioChunk,
 *   !proto.transcription.TranscriptionResult>}
 */
const methodDescriptor_TranscriptionService_Transcribe = new grpc.web.MethodDescriptor(
  '/transcription.TranscriptionService/Transcribe',
  grpc.web.MethodType.UNARY,
  proto.transcription.AudioChunk,
  proto.transcription.TranscriptionResult,
  /**
   * @param {!proto.transcription.AudioChunk} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.transcription.TranscriptionResult.deserializeBinary
);


/**
 * @param {!proto.transcription.AudioChunk} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.transcription.TranscriptionResult)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.transcription.TranscriptionResult>|undefined}
 *     The XHR Node Readable Stream
 */
proto.transcription.TranscriptionServiceClient.prototype.transcribe =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/transcription.TranscriptionService/Transcribe',
      request,
      metadata || {},
      methodDescriptor_TranscriptionService_Transcribe,
      callback);
};


/**
 * @param {!proto.transcription.AudioChunk} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.transcription.TranscriptionResult>}
 *     Promise that resolves to the response
 */
proto.transcription.TranscriptionServicePromiseClient.prototype.transcribe =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/transcription.TranscriptionService/Transcribe',
      request,
      metadata || {},
      methodDescriptor_TranscriptionService_Transcribe);
};


module.exports = proto.transcription;

