# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: transcription.proto for package 'transcription'

require 'grpc'
require 'transcription_pb.rb'
module Transcription
  module TranscriptionService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'transcription.TranscriptionService'

      rpc :Transcribe, stream(::Transcription::AudioChunk), stream(::Transcription::TranscriptionResult)
    end

    Stub = Service.rpc_stub_class
  end
end
