# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcription.proto

require 'google/protobuf'


descriptor_data = "\n\x13transcription.proto\x12\rtranscription\" \n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\")\n\x13TranscriptionResult\x12\x12\n\ntranscript\x18\x01 \x01(\t2c\n\x14TranscriptionService\x12K\n\nTranscribe\x12\x19.transcription.AudioChunk\x1a\".transcription.TranscriptionResultb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Transcription
  AudioChunk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("transcription.AudioChunk").msgclass
  TranscriptionResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("transcription.TranscriptionResult").msgclass
end
